### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka/plugin-Timeline#1]
Please test functionality of the Timeline plugin, including:

- Adding, editing metadata & removing timelines
- Editing all advance search fields in timeline Item Query
- Using date values of different granularity, including year, year and month, year/month/day, time, etc. (see ISO 8601 note below for formatting)
- Timeline block functionality in ExhibitBuilder
- Timeline shortcode (use format `[timeline title='']` with timeline title value inserted)
- Timeline browse/block/shortcode functionality in different themes and browsers

Some expected behavior to note (these should eventually be covered in plugin documentation, but just FYI for now):
- After initially creating a Timeline, it will appear "empty" until you Edit Item Query, i.e. search for items to populate the timeline.
- Timeline discrete dates and intervals must be in ISO 8601 format, i.e. `YYYY-MM-DDThh:mm:ss`, with a `/` separator between dates in interval values. If date/interval values are not formatted correctly, the item will be left out of the timeline.
- If an item has both a discrete date value and interval value in the fields mapped by timeline metadata, the interval value will take precedence over the discrete value.

Please let me know if you have any questions. Thank you!

**Comment by katknow** [comment]
I'm maybe missing it, but how do you remove a query from a timeline? I see where you can delete the full timeline, I did an initial keyword search and it added everything related to that key word and I don't see where I can edit it.

**Comment by matthewjmckinley** [comment]
You can edit a Timeline query by clicking "Edit Item Query" under the timeline's entry in the main Timeline browse page, or on the Timeline's 'show' page by clicking "Edit Items Query" (that's a typo, will fix).

From the Edit Query page, you can add to or change the Query but you can't really 'delete'. The best you can do is remove all query parameters, which would then show all items in your Omeka instance since the query isn't filtering anything out. If you wanted to start 'from scratch' deleting and recreating the timeline would be the best option.

**Comment by katknow** [comment]
Thanks for the clarification! The starting 'from scratch' is what I was curious about and is what I will do. I had tried to change the keyword and realized I was just adding more and more rather than changing anything.

**Comment by katknow** [comment]
I'm almost done with this, but I'm not having luck with intervals. Just to make sure I'm understanding correctly, the format of an interval date would be `YYYY-MM-DDThh:mm:ss/YYYY-MM-DDThh:mm:ss`?

**Comment by matthewjmckinley** [comment]
I have tested with a few different levels of granularity for intervals (YYYY/YYYY, YYYY-MM/YYY-MM-DDThh:mm, YYYY-MM-DDThh:mm:ss/YYYY-MM-DDThh:mm:ss) and they all work on my instance. My 'full' test value, for example, is `1942-09-11T12:12:12/1979-03-02T11:08:00` and the interval parses correctly both in the timeline graphic and the Display value that appears at the top of the timeline slide. Are you getting any error messages, either on screen, in the error.log or in the console tab when you right click and 'Inspect Element' on the timeline?

**Comment by matthewjmckinley** [comment]
For the disappearing/flashing arrows when viewing a Timeline in the Thanks Roy theme, I have confirmed that this is also happening for me--the arrows will flash when clicked, and while they eventually seem to advance to the next slide, it is taking anywhere between 1 to 6 tries each time.

I've looked at the logs and console and don't see any obvious errors happening with the JS. @kimisgold , would you mind taking a look at how this module's timelines are (mis)behaving in the Thanks Roy theme on classic?

**Comment by kimisgold** [comment]
Thanks Roy has a style that gives active buttons `z-index: 1` to prevent outline styles from getting clipped by adjacent elements. The plugin could probably provide a more specific style to prevent this. We could do 
```
button.tl-slidenav-next:active {
    z-index: 10;
}
```
or 
```
.tl-slidenav-next {
    z-index: 10 !important;
}
```

**Comment by matthewjmckinley** [comment]
Thanks, Kim! I've added a commit with the above CSS for the next and previous slidenav buttons that seems to fix this issue. Give it a try and see if it fixes things. Beyond that, and the granularity problem we've discussed above, let me know if there's any other issues to address here.

@allanaaa I've also added you as an assignee at Sharon's request--would you mind doing some quick testing of this module to see if you spot anything, before I close it out and open a documentation issue? Thanks!

**Comment by katknow** [comment]
This now works smoothly with the Thanks Roy theme. I'm still not having luck with intervals. Nothing is in my error log or appearing on the screen, but hen I click on the console tab in Inspect Element I get all of these messages (although many of them look like they're probably not relevant, I'm not sure):

`Uncaught TypeError: e.indexOf is not a function
    load jQuery
    <anonymous> https://dev.omeka.org/katknow/OmekaTesting/plugins/YouTubeImport/views/public/javascripts/YoutubeImport.js?v=3.0.3:1
[jquery.min.js:2:84932](https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js)
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. [Icons.less:27:1](webpack://TL/src/less/icons/Icons.less)
Unknown property ‘-moz-box-shadow’.  Declaration dropped. [Mixins.less:107:4](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-border-radius’.  Declaration dropped. [Mixins.less:82:5](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘speak’.  Declaration dropped. [TL.TimeNav.less:28:3](webpack://TL/src/less/timenav/TL.TimeNav.less)
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. [TL.TimeNav.less:37:3](webpack://TL/src/less/timenav/TL.TimeNav.less)
Unknown property ‘-moz-border-radius’.  Declaration dropped. [Mixins.less:82:5](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘line-clamp’.  Declaration dropped. [TL.TimeMarker.less:155:5](webpack://TL/src/less/timenav/TL.TimeMarker.less)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:12:1](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:12:1](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:12:1](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:12:1](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-border-radius’.  Declaration dropped. [Mixins.less:82:5](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘line-clamp’.  Declaration dropped. [TL.TimeEra.less:108:5](webpack://TL/src/less/timenav/TL.TimeEra.less)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:12:1](webpack://TL/src/less/core/Mixins.less)
Error in parsing value for ‘-webkit-perspective’.  Declaration dropped. [TL.Animate.less:3:1](webpack://TL/src/less/animation/TL.Animate.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-background-size’.  Declaration dropped. [TL.Slide.less:24:5](webpack://TL/src/less/slider/TL.Slide.less)
Unknown property ‘-moz-background-size’.  Declaration dropped. [TL.Slide.less:188:4](webpack://TL/src/less/slider/TL.Slide.less)
Unknown property ‘-moz-border-radius’.  Declaration dropped. [Mixins.less:82:5](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘line-clamp’.  Declaration dropped. [TL.SlideNav.less:30:7](webpack://TL/src/less/slider/TL.SlideNav.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘speak’.  Declaration dropped. [TL.SlideNav.less:90:2](webpack://TL/src/less/slider/TL.SlideNav.less)
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. [TL.SlideNav.less:97:2](webpack://TL/src/less/slider/TL.SlideNav.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [Mixins.less:51:2](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-opacity’.  Declaration dropped. [Mixins.less:53:4](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-box-shadow’.  Declaration dropped. [Mixins.less:107:4](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-box-shadow’.  Declaration dropped. [Mixins.less:107:4](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-border-radius’.  Declaration dropped. [Mixins.less:82:5](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-border-radius’.  Declaration dropped. [Mixins.less:82:5](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-box-shadow’.  Declaration dropped. [Mixins.less:107:4](webpack://TL/src/less/core/Mixins.less)
Unknown property ‘-moz-box-shadow’.  Declaration dropped. [admin-bar.css:15:25](https://dev.omeka.org/katknow/OmekaTesting/application/views/scripts/css/admin-bar.css?v=3.0.3)
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. [style.css:13:29](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Expected declaration but found ‘*’.  Skipped to next declaration. [style.css:729:5](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Expected declaration but found ‘*’.  Skipped to next declaration. [style.css:770:5](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Expected declaration but found ‘*’.  Skipped to next declaration. [style.css:771:5](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Expected declaration but found ‘*’.  Skipped to next declaration. [style.css:777:5](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Expected declaration but found ‘*’.  Skipped to next declaration. [style.css:778:5](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Unknown property ‘-moz-background-clip’.  Declaration dropped. [style.css:800:26](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Expected declaration but found ‘*’.  Skipped to next declaration. [style.css:816:5](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Expected declaration but found ‘*’.  Skipped to next declaration. [style.css:817:5](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Expected declaration but found ‘*’.  Skipped to next declaration. [style.css:818:5](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Unexpected token ‘16’ in media list. [style.css:1280:35](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Error in parsing value for ‘font-weight’.  Declaration dropped. [style.css:1575:18](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Error in parsing value for ‘margin’.  Declaration dropped. [style.css:1618:18](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Unexpected token ‘16’ in media list. [style.css:1628:35](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Unexpected token ‘16’ in media list. [style.css:1941:35](https://dev.omeka.org/katknow/OmekaTesting/themes/ThanksRoy/css/style.css?v=3.0.3)
Use of Mutation Events is deprecated. Use MutationObserver instead. [jquery.min.js:2:41514](https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js)`

For the most part, things seem to be working as expected. I was able to get all of the different fields for the item query to work and get different combos to work together, timeline works in exhibit builder, shortcode works, etc.

I'm not sure if it's related because I can still see and use the timeline on its various pages, but the last pull I did resulted in this error message on my homepage:

`Warning
: array_keys() expects parameter 1 to be array, bool given in
/var/www/html/katknow/OmekaTesting/application/libraries/Omeka/Db/Table.php
on line
133


Warning
: in_array() expects parameter 2 to be array, null given in
/var/www/html/katknow/OmekaTesting/application/libraries/Omeka/Db/Table.php
on line
389


Warning
: array_keys() expects parameter 1 to be array, bool given in
/var/www/html/katknow/OmekaTesting/application/libraries/Omeka/Db/Table.php
on line
133


Warning
: Invalid argument supplied for foreach() in
/var/www/html/katknow/OmekaTesting/application/libraries/Omeka/Db/Table.php
on line
366


Fatal error
: Uncaught Error: Class 'EXHIBIT' not found in /var/www/html/katknow/OmekaTesting/application/libraries/Omeka/Db/Table.php:682 Stack trace: #0 /var/www/html/katknow/OmekaTesting/application/libraries/Omeka/Db/Table.php(653): Omeka_Db_Table->recordFromData(Array) #1 /var/www/html/katknow/OmekaTesting/application/libraries/Omeka/Db/Table.php(281): Omeka_Db_Table->fetchObjects(Object(Omeka_Db_Select)) #2 /var/www/html/katknow/OmekaTesting/application/libraries/globals.php(1749): Omeka_Db_Table->findBy(Array, 2) #3 /var/www/html/katknow/OmekaTesting/themes/ThanksRoy/functions.php(39): get_records('EXHIBIT', Array, 2) #4 /var/www/html/katknow/OmekaTesting/themes/ThanksRoy/index.php(12): thanksroy_exhibit_builder_display_random_featured_records('exhibit', 2) #5 /var/www/html/katknow/OmekaTesting/application/libraries/Omeka/View.php(114): include('/var/www/html/k...') #6 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/View/Abstract.php(889): Omeka_View->_run('/var/www/html/k...') #7 /var/www/html/katknow in
/var/www/html/katknow/OmekaTesting/application/libraries/Omeka/Db/Table.php
on line
682`

**Comment by matthewjmckinley** [comment]
@katknow can you describe how the intervals are not working and/or post a screenshot? Does the rest of the timeline load, or not at all? Do the console/log messages look the same across browsers?

I'm seeing a lot of javascript warnings related to the Timeline/TL object, but none of these should necessarily be causing the timeline to crash/not be displayed.

The main page error message looks like it's related to the Thanks, Roy theme specifically and not necessarily the Timeline plugin.

**Comment by katknow** [comment]
@matthewjmckinley the intervals are just not appearing. At all. The rest of the timeline loads and looks completely normal. I even tried copying and pasting your example directly into the date field with no luck.

**Comment by allanaaa** [comment]
The basics of the timeline plugin work for me. I'll look at intervals and themes next. 

One small quibble (not sure if this is plugin or core): For this plugin, the "View public page" button in the right-hand side will open in the same tab rather than open a new tab, inconsistently across the installation. Pages, exhibits, and collections will open in a new tab, but not timelines.

**Comment by allanaaa** [comment]
Intervals work for me. I only tested YYYY-MM-DD/YYYY-MM-DD in Coverage but that worked immediately.

Every theme works and looks pretty good. Seasons is highlighting the zoom/etc. buttons in a way that the other themes aren't:
![seasons](https://user-images.githubusercontent.com/28012148/202299849-52a116ff-da44-43eb-ba5b-cba6e32eb203.PNG)

Also, I really appreciate the help-text you put in the module settings pages.

**Comment by matthewjmckinley** [comment]
OK I can replicate it now that I am cycling through the seasons. Sizing aside, I think the different colors for Autumn and Spring look kinda nice? But the timeline should probably display in a uniform way across themes regardless, especially with that terribly low contrast in Summer. I'll see if it's something I can override in the module's styling.

**Comment by matthewjmckinley** [comment]
@allanaaa OK I addressed the Seasons controls background color in the latest commit, as well as some spacing issues where the timeline year axis, next button title caption, etc. were getting cut off. Please test with seasons and other themes to make sure everything still looks good!

**Comment by matthewjmckinley** [comment]
@katknow I think since @allanaaa and I are both able to see the intervals, it may in fact be an issue with just your instance. Which to my mind we can move forward and address with a plugin update/fix later if we get any complaints in the forums.

Otherwise, does this plugin look good to move on to documentation phase?

**Comment by katknow** [comment]
@matthewjmckinley the intervals are the only issue I'm having, and I'm guessing you're right and it's just an issue with my instance.
