### ISSUE TITLE
Testing: New Timeline Features

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka/plugin-Timeline#13]
Please pull latest code and test new bug fixes/features:
- https://github.com/omeka/plugin-Timeline/issues/9 -- You should now be able to save a timeline without an item date, interval, title, or description (or any combination thereof)
- https://github.com/omeka/plugin-Timeline/issues/11
- https://github.com/omeka/plugin-Timeline/issues/7 
   - Search By Metadata interactions should now be removed
   - Test new truncate setting in timeline metadata -- truncates title to 2 lines and description to 4 lines, these can be adjusted by users in the /views/public/timelines/show.php file, the two `--webkit-line-clamp` CSS properties
- https://github.com/omeka/plugin-Timeline/issues/10 timelines should now be sortable. `Reset Timeline Order` button resets to order added. Newly added timelines appear at top of list until they are re-ordered.

Thanks!

**Comment by allanaaa** [comment]
https://github.com/omeka/plugin-Timeline/assets/28012148/f030b36b-e2ad-4f34-abe4-2b4e7872f3fe

This may be an interaction with other plugins, but I'm getting strange height behaviour when the window is resized.

**Comment by allanaaa** [comment]
When I try to create a new timeline, without changing any of the settings, I get 

```

Omeka has encountered an error

Zend_Db_Statement_Mysqli_Exception

    Mysqli prepare error: Unknown column 'font' in 'field list'

Zend_Db_Statement_Mysqli_Exception: Mysqli prepare error: Unknown column 'font' in 'field list' in /var/www/html/amayer/amayer-c/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /var/www/html/amayer/amayer-c/omeka/application/libraries/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `om...')
#1 /var/www/html/amayer/amayer-c/omeka/application/libraries/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `om...')
#2 /var/www/html/amayer/amayer-c/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `om...')
#3 /var/www/html/amayer/amayer-c/omeka/application/libraries/Omeka/Db.php(80): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#4 /var/www/html/amayer/amayer-c/omeka/application/libraries/Omeka/Db.php(257): Omeka_Db->__call('query', Array)
#5 /var/www/html/amayer/amayer-c/omeka/application/libraries/Omeka/Record/AbstractRecord.php(542): Omeka_Db->insert('omeka_timelines', Array)
#6 /var/www/html/amayer/amayer-c/omeka/application/libraries/Omeka/Controller/AbstractActionController.php(204): Omeka_Record_AbstractRecord->save(false)
#7 /var/www/html/amayer/amayer-c/omeka/plugins/Timeline/controllers/TimelinesController.php(42): Omeka_Controller_AbstractActionController->addAction()
#8 /var/www/html/amayer/amayer-c/omeka/application/libraries/Zend/Controller/Action.php(516): Timeline_TimelinesController->addAction()
#9 /var/www/html/amayer/amayer-c/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#10 /var/www/html/amayer/amayer-c/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/html/amayer/amayer-c/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(106): Zend_Controller_Front->dispatch()
#12 /var/www/html/amayer/amayer-c/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/html/amayer/amayer-c/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#14 /var/www/html/amayer/amayer-c/omeka/admin/index.php(28): Omeka_Application->run()
#15 {main}

```

**Comment by allanaaa** [comment]
This also happens when I edit and save an existing timeline (again without actually changing any settings).

**Comment by allanaaa** [comment]
Also, 

>Truncate title/description
>Truncate title and description text to fit in timeline slide without scrolling.

It’s always going to scroll vertically, never horizontally? We should say “without vertical scrolling” in the interface.

**Comment by matthewjmckinley** [comment]
@allanaaa I'll update the info and look into the resize issue.

For the "Unknown column 'font'", the only thing I can think is maybe you installed an earlier version of the Timeline plugin to test before I added the font setting (https://github.com/omeka/plugin-Timeline/commit/4ae03ea464f6fed35cf4c62d2800f8f92b94625c), and then pulled updates to the code without fully re-installing, so it never picked up that 'new' field on a fresh plugin install. If a plugin has already been released, I would put any new database fields in the `hookUpgrade()`, but since I added that feature pre-release I didn't do so.

Would it be possible for you to uninstall and re-install from the latest code? I realize this would mean losing your existing timelines, so maybe there's another instance on the test server or something you can install on?

**Comment by allanaaa** [comment]
Not a problem. Uninstalling and reinstalling did fix that issue. The resizing is still happening. 

I think we might also need some interface context for the drag-and-drop list of timelines. Something to explain that this affects the /timeline public page. There should be a link right on the Timeline config page to the public page too. 

Mine's appearing like this: 
http://dev.omeka.org/amayer/amayer-c/omeka/timeline

The `.timeline` divs need some bottom margin or padding.

**Comment by matthewjmckinley** [comment]
New commits are in.

I've fixed the resizing issue by reinstating the fixed height for the timeline, which I `unset` at one point as the bottom dates were getting cut off, and used `overflow` instead.

I added some context to the timeline admin browse page as well as a link to the public timeline browse page. Let me know if the text works!

Finally, I played around with a bunch of themes and the `.timeline` divs seem properly padded wherever I looked. Might be a theme issue? Can I ask what theme you're using in the link above?

**Comment by allanaaa** [comment]
It's Thanks Roy, in the form of the default theme that ships with the core install. I did update the core just now from github and nothing changed, though I'm sure that doesn't pull the latest thanks roy code.

**Comment by allanaaa** [comment]
The text link should open in a new window/tab by default. And the sentence should end with a period. It's fine; I'd rather have a big green "View Public Page" button or something.

On the front end, the resizing is fixed but now I can see the description text partially underneath the timeline. 
<img width="926" alt="Screenshot 2023-08-24 at 1 31 18 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/2f2c0a62-7ca2-48ec-971c-33d0b024faba">

I have the title and description truncated now, and I'm not crazy about the way it looks. Specifically I would rather have the title show up way smaller than have it truncate, and I would prefer to show the full title and truncate the description, rather than ever truncate the title unless absolutely necessary. As it is, you can't see the full title when you hover over the link or the flag. But you can see the full title if you go back or forward to another slide and then look next to the arrow..... It's just not very helpful. It seems like a lot of wasted whitespace. 

The height of the text half should at least equal the image height:
<img width="910" alt="Screenshot 2023-08-24 at 1 39 02 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/ecc9b55a-4645-492a-9901-2de80b8a24d9">

**Comment by allanaaa** [comment]
> Finally, I played around with a bunch of themes and the `.timeline` divs seem properly padded wherever I looked. Might be a theme issue? Can I ask what theme you're using in the link above?

I think what you're seeing is some default top and bottom margins on the h2s, that coincidentally provide some nice spacing. Thanks Roy has a `margin-top:0` on h2s. You should put some explicit margin or padding on the .timeline divs.

**Comment by matthewjmckinley** [comment]
Description bug fixed, helper text/link updated and bottom margin added on timeline divs.

What you're asking for truncation/resizing seems simple, but is more complex in execution with CSS/JS from what I can tell. Within the context of the timeline.js container machinations, it's proving to be a tricky thing to dynamically read the image size and resize the accompanying text caption appropriately--especially since it's two different divs for title and caption. Resizing the title instead of truncating may also be tricky since the title text is all different sizes depending on the theme used.

All this is to say that anything is possible, but I've spent a few days trying to achieve dynamic truncating/resizing without much headway. It may make more sense to ask Kim about this when she returns--her CSS solution, if it exists, will likely be more elegant than whatever I could cobble together.

**Comment by allanaaa** [comment]
Sorry, just noticed this on the public Timelines page: why are the descriptions being truncated in this way? I guess I didn't have long descriptions before now. It is a bit weird. I can't find any code governing that.

<img width="1065" alt="Screenshot 2023-08-28 at 10 50 03 AM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/3fc5c5b1-7aa7-405e-ae95-18adca079a09">



Also, in slides the ellipsis is being appended even to titles that are showing in full. I think it's only happening when the title is on two lines, not ones that are short enough to be a single line. All three of these slides are showing the full item title. 

<img width="1224" alt="Screenshot 2023-08-28 at 11 00 52 AM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/589e1907-fbf1-4f50-a939-7200465e12db">
<img width="1250" alt="Screenshot 2023-08-28 at 11 00 01 AM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/7895c7f6-440f-402c-8145-4c04933cea3d">
<img width="1282" alt="Screenshot 2023-08-28 at 10 59 24 AM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/8794179e-c952-4f2e-a55a-3f2a8d023bed">



The rest of the stuff you fixed looks great, thanks. Let me mull over the truncating a bit more, before we kick the can over to Kim. I feel pretty sure that because we know the max image height we can have a little more room to offer the text half, but because you're doing it with JS I may not be able to work with what you've got so far.

**Comment by allanaaa** [comment]
So, digging in:

- You've put the line-clamp on the headline-container, which is messing up the display:flex that needs to be there. So, I moved that down to the h2 a, so it's also blue instead of black. 
- We have a fixed height on the timeline, and a fixed max-height on the media (329px), so we can set max heights on the text container, and the slide container, to help us along. 

```
.tl-text {
  max-height: 320px;
  overflow: hidden;
display:table-cell;
vertical-align:top;
}

.tl-media {
display:table-cell;
float:none!important;
}

(to match the other one - should help keep heights even - but maybe not necessary)

.tl-text-content-container {
  height: 320px;
}

(to ensure the fadeout stays at the very bottom of a tall div)

.tl-text-content-container::after {
  content: '';
  width: 100%;
  height: 50px;
  position: absolute;
  left: 0;
  bottom: 0;
  background: linear-gradient(transparent, white);
}

(50px height should cover two lines of text, for a more gradual indicator. But feel free to mess with this.)

.tl-headline a {
  margin-top: 0;
  display: -webkit-box;
  -moz-box-orient: vertical;
  overflow: hidden;
  -webkit-line-clamp: 4;
}

(I changed line-clamp to 4, which is a good compromise I think? Or we could remove it altogether.)

.tl-timeline p {
  margin-top: 0px;
  margin-bottom: 0px;
}
```

The only problem with this solution is the fadeout part isn’t conditional, so you could end up with a final line or two of text being faded even though it’s all appearing. I don’t mind that so much. 
If you want, the way to do that with JS would be like "if headline height + date height + text height > 320px, add the ::after; otherwise, don't."

**Comment by allanaaa** [comment]
Here's how it looks. I toggled the line-clamp from "4" off entirely on the one slide with a long headline.
Note that there will be some unnecessary fade, for example on the word "Philadelphia" in the last one. 

<img width="1147" alt="Screenshot 2023-08-28 at 2 48 48 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/213c5a06-ace2-4c03-bbd6-6298ae5d9d25">
<img width="1154" alt="Screenshot 2023-08-28 at 2 48 59 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/bea65a2c-3312-4f64-9868-3db02b1730f9">
<img width="1175" alt="Screenshot 2023-08-28 at 2 49 05 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/cf1c2b00-1260-4e45-89c4-161023199bb7">
<img width="1161" alt="Screenshot 2023-08-28 at 2 49 12 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/24be64cb-a2f0-4db2-a627-37fdc06f527d">
<img width="1147" alt="Screenshot 2023-08-28 at 2 49 22 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/c1ecd6ad-1f78-4cb0-9146-ceb84b39c191">
<img width="1147" alt="Screenshot 2023-08-28 at 2 49 34 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/7d195100-f3dc-4a6f-afb6-c35aba069171">
<img width="1146" alt="Screenshot 2023-08-28 at 2 49 42 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/4ccef778-f5e1-4924-bfc8-93789ffae759">
<img width="1140" alt="Screenshot 2023-08-28 at 2 49 57 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/4feff47e-85f8-44ec-a877-2bb65f0ae3b6">
<img width="1139" alt="Screenshot 2023-08-28 at 2 50 05 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/901c208b-cedb-4253-8baf-1ab99566aada">

**Comment by allanaaa** [comment]
Hard to test all the font combos because all of my code is being run in-browser, but here are a few:
<img width="1154" alt="Screenshot 2023-08-28 at 3 03 14 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/102cd61f-4651-43bd-a80c-75d27abe142a">
<img width="1138" alt="Screenshot 2023-08-28 at 3 04 29 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/db29ad3d-462f-4d01-9a01-5f0799edfa9b">
<img width="1159" alt="Screenshot 2023-08-28 at 3 06 22 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/ace98a0d-529e-43ae-9cca-40dd7e92ef29">

**Comment by allanaaa** [comment]
This one has a font big enough that the title takes up all available space, so you can see what the fadeout looks like there:

<img width="1062" alt="Screenshot 2023-08-28 at 3 31 21 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/a276f40c-6dd3-4c34-973a-afdd1423bb9f">
<img width="1063" alt="Screenshot 2023-08-28 at 3 31 35 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/2c4a5824-3c04-43c8-ab7c-416db44d086b">

**Comment by matthewjmckinley** [comment]
Well, I stand corrected! This is great work. I fiddled with it a bit to get it work with the existing css and jquery, but I think it's testing OK in the different browsers and fonts I've looked at. Fix is in latest commit.

I agree that clamping the Title doesn't always look ideal, but I think it's better than having a run-on title push the description off--if there's a description for the slide and they've chosen to display it, I think it should still appear even when truncated. Also, for a few fonts the top of the 'hidden' overflow text on the title is still showing beyond the ellipsis--I couldn't find a way to fix this without making the line-height comically large, so that may be something people will have to fiddle with on a case-by-case (or font-by-font) basis.

LMK if anything else looks crazy!

**Comment by allanaaa** [comment]
Looks good now! So, with truncation:

<img width="969" alt="Screenshot 2023-09-05 at 4 25 41 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/a8ef95ee-da06-4fa6-813c-3dc4a238449a">

and without:

<img width="968" alt="Screenshot 2023-09-05 at 4 25 50 PM" src="https://github.com/omeka/plugin-Timeline/assets/28012148/cc704e7d-93d6-4b29-9fd1-aff936f9f3f9">

My dream feature would be for the vertical scrollbar to sit inside the arrows, but I've seen the code and I know that's not really possible. 

I think this is about as good as we can get it. Every other issue seems to be resolved. 👍
