### ISSUE TITLE
Timeline left & right arrows disappearing

### ISSUE THREAD

**Issue by allanaaa** [omeka/plugin-Timeline#6]
In the Thanks Roy theme, the arrow you've just clicked disappears for a few seconds. It's not just invisible but actually gone (no link, no mouseover):
http://dev.omeka.org/amayer/amayer-c/omeka/timeline/show/1

![timeline](https://user-images.githubusercontent.com/28012148/215800973-e18a6baf-742c-4e61-af62-0960ba1b4771.gif)

Happening in both Firefox and Chrome for me, on the left and right arrows (+ text). The missing arrow comes back if you click anywhere (i.e. it appears, then you can click on it again as a link), or click out of the browser. I don't know if it's some sort of leftover :active artifact, or an onClick action. Only in the Thanks Roy theme that I can see.

**Comment by matthewjmckinley** [comment]
I can't replicate this, and it seems very similar to a bug Katherine found that I thought we fixed in the previous testing issue (https://github.com/omeka/plugin-Timeline/issues/1#issuecomment-1303763998) -- is this still happening with the latest version of the Timeline plugin code and Thanks Roy theme?

**Comment by matthewjmckinley** [comment]
NM I see it happening in Chrome. I'll look into it!

**Comment by matthewjmckinley** [comment]
@allanaaa OK this should be fixed, please test with latest code.
